//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string award { get; set; }
        public string gift { get; set; }
        public Nullable<double> cash_price { get; set; }
        public Nullable<int> month_id { get; set; }
        public Nullable<int> year_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Month Month { get; set; }
        public virtual Year Year { get; set; }
    }
}
