//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Attendences = new HashSet<Attendence>();
            this.Awards = new HashSet<Award>();
            this.Leave_Appliaction = new HashSet<Leave_Appliaction>();
            this.Notices = new HashSet<Notice>();
        }
    
        public int id { get; set; }
        public string employee_image { get; set; }
        public string employee_full_name { get; set; }
        public Nullable<int> employee_departament_id { get; set; }
        public string employee_phone { get; set; }
        public Nullable<System.DateTime> employee_date_of_birth { get; set; }
        public Nullable<int> employee_gender_id { get; set; }
        public string employee_local_address { get; set; }
        public string employee_permanent_address { get; set; }
        public Nullable<int> designation_id { get; set; }
        public string employee_father_name { get; set; }
        public string employee_email { get; set; }
        public string employee_password { get; set; }
        public string employee_work_duration { get; set; }
        public Nullable<System.DateTime> date_of_join { get; set; }
        public Nullable<int> join_salary { get; set; }
        public Nullable<int> exit_date { get; set; }
        public Nullable<int> employee_status_id { get; set; }
        public string resume_files { get; set; }
        public string offer_letter { get; set; }
        public string joinning_letter { get; set; }
        public string contract_and_agreement { get; set; }
        public string id_proof { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Award> Awards { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Employee_Status Employee_Status { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Appliaction> Leave_Appliaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notice> Notices { get; set; }
    }
}
