//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int id { get; set; }
        public string item_name { get; set; }
        public string purchase_from { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> amount_price { get; set; }
        public string attach_bill_file { get; set; }
    }
}
