//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ocassions { get; set; }
        public Nullable<int> month_id { get; set; }
    
        public virtual Month Month { get; set; }
    }
}
