//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<Attendence_Status> Attendence_Status { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Departament> Departaments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Leave_Appliaction> Leave_Appliaction { get; set; }
        public virtual DbSet<Leave_Status> Leave_Status { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Notice_Status> Notice_Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_Leave> Type_of_Leave { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    }
}
