//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Appliaction
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<System.DateTime> app_date { get; set; }
        public Nullable<int> leave_type_id { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> app_on_date { get; set; }
        public Nullable<int> leave_status_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Leave_Status Leave_Status { get; set; }
        public virtual Type_of_Leave Type_of_Leave { get; set; }
    }
}
